#!/usr/bin/env bash
#
# Backup local & remote data, store backups and checksums in a
# tar file, and store in central location, organized by date

CONFIG=./config
LOG=

init() {
  source $CONFIG \
    || logLevel=4 err "error loading config file $CONFIG"
  verifyConfig

  [[ $logLevel -le 3 ]] && return 0
  # next 2 lines are only executed if in debug mode:
  # enable '-v' for many tools and echo the contents of the config file
  v=-v
  sed '/^\s*\#/d; /^\s*$/d' "$CONFIG" >> /dev/stderr
}

verifyConfig() {
  local readonly msgPrefix="config validation error:"

  [[ $logLevel -le 4 && $logLevel -ge 1 ]] \
    || logLevel=4 err "log level not in [1-4]"

  [[ -n $destRoot ]] \
    || err "$msgPrefix \$destRoot not set"

  mkdir -p "$destRoot" \
    || err "$msgPrefix $destRoot is not a directory"

  [[ -w $destRoot ]] \
    || err "$msgPrefix $destroot is not writable"

  [[ -n $targetsDir ]] \
    || err "$msgPrefix \$targetsDir not set"

  [[ -d $targetsDir ]] \
    || err "$msgPrefix $targetsDir is not a directory"

  [[ -n $zipper ]] \
    || err "$msgPrefix \$zipper not set"

  [[ -n $zipperExt ]] \
    || err "$msgPrefix \$zipperExt not set"

  command -v "${zipper%% *}" &> /dev/null \
    || err "$msgPrefix command '$zipper' not found"

  [[ -n $hasher ]] \
    || err "$msgPrefix \$hasher not set"

  [[ -n $hasherExt ]] \
    || err "$msgPrefix \$hasherExt not set"

  command -v "${hasher%% *}" &> /dev/null \
    || err "$msgPrefix command '$hasher' not found"

  [[ ${jobLimit:-1} -ge 1 ]] \
    || err "$msgPrefix "
}

log() {
  local readonly lvl=$1
  local readonly msg=$2
  [[ $lvl > $logLevel ]] && return 0

  local readonly timestamp=$(date +'[%D] [%T]')
  case $lvl in
    1) prelog='[ERR!]' ;;
    2) prelog='[WARN]' ;;
    3) prelog='[INFO]' ;;
    4) prelog='[DBUG]' ;;
    *) err "invalid log level: $lvl" ;;
  esac
  echo "$prelog $timestamp ${targetName:+[$targetName] }$msg" >> /dev/stderr
}

err() {
  log 1 "$1"
  exit 1
}

parseServerFile() {
  local targetFile=$1
  while read ln; do
    # compress blank space in lines
    local line=$(tr -s '[:blank:]' <<< "$ln")
    # support comments in target files
    [[ $line == \#* ]] && continue
    # parse the target file assuming the lines are in a 'key = value' format:
    local key=${line%% =*}
    local val=${line#*= }
    case $key in
      type) targetType=$val ;;
      host) targetHost=$val ;;
      user) targetUser=$val ;;
      pass) targetPass=$val ;;
      port) targetPort=$val ;;
      include) include=$val ;;
      preCmnd) preCmnd=$val ;;
      args) targetArgs=$val ;;
      *) log 2 "Unrecognized key '$key' in target" ;;
    esac
    log 4 "$key=$val"
  done < "$targetFile"
}

filesBackup() {
  local dumpFile=$targetName.tar

  log 3 "creating files backup: ($include) > $dumpFile"
  $preCmnd tar $targetArgs $v -c $include > "$dumpFile" \
    || err "error creating tar backup"

  zipAndHashDump "$dumpFile"
}

sqlBackup() {
  dbDumpArgs="${targetHost:+"--host=$targetHost"}
              ${targetPort:+"--port=$targetPort"}
              $v"
  case $targetType in
    mysql)
      dbDumpArgs="${targetArgs:-$defaultMysqlArgs}
                  ${targetUser:+"--user=$targetUser"}
                  ${targetPass:+"--password=$targetPass"}
                  $dbDumpArgs"
      dbDump=mysqldump
      ;;
    psql)
      dbDumpArgs="${targetArgs:-$defaultPsqlArgs}
                  ${targetUser:+"--username=$targetUser"}
                  $dbDumpArgs"
      dbDump=pg_dump
      ;;
  esac

  log 3 "target databases are: $include"

  for db in $include; do
    log 3 "starting backup process for $db"
    backupDB "$db"
  done
}

backupDB() {
  local dbName=$1
  local dumpFile=$dbName.sql

  log 3 "dumping database: $dbName > $dumpFile"
  $preCmnd $dbDump $dbDumpArgs "$dbName" > "$dumpFile" \
    || err "error creating database backup $dumpFile"

  zipAndHashDump "$dumpFile"
}

zipAndHashDump() {
  local dumpFile=$1
  local dumpFileZip=$dumpFile.$zipperExt
  local dumpFileHash=$dumpFileZip.$hasherExt

  log 3 "compressing dump: $dumpFile > $dumpFileZip"
  $zipper "$dumpFile" > "$dumpFileZip" \
    || err "error creating compressed dump $dumpFileZip"

  rm $v "$dumpFile"

  log 3 "creating $hasherExt checksum: $dumpFileZip > $dumpFileHash"
  $hasher "$dumpFileZip" > "$dumpFileHash" \
    || err "error creating checksum $dumpFileHash"
}

getDestFile() {
  destFile=$destDir/${targetType}_backup_${targetName}_$(date +%y_%m_%d).tar
  [[ ! -e $destFile ]] && return

  log 2 "destination file $destFile already exists"
  local tag=0
  local initialName=$destFile
  while [[ -f $destFile ]]; do
    (( tag++ ))
    destFile=${initialName%.tar}-$tag.tar
    log 4 "trying destination file name: $destFile"
  done
}

backupTarget() {
    targetName=$1
    log 3 "[BACKUP START]"

    parseServerFile "$serverFile"
    log 3 "parsed config for target"

    workdir=$(mktemp -d)
    log 4 "workspace for backup is $workdir"
    cd "$workdir" \
      || err "$workdir can't be accessed"

    getDestFile
    log 3 "storing backups in file: $destFile"

    case $targetType in
      mysql|psql) (sqlBackup)   ;;
      files)      (filesBackup) ;;
      *) (err "unrecognized backup type: '$targetType'") ;;
    esac || { log 2 "[BACKUP FAIL]"; return; }

    tar $v -c ./* > "$destFile" \
      || err "error creating tar file $destFile"

    chmod $v "${backupPerms:-600}" "$destFile" \
      || log 2 "error setting permissions on $destFile"

    log 4 "deleting temporary workspace: $workdir"
    cd - > /dev/null
    rm $v -rf "$workdir"

    log 3 "[BACKUP DONE]"
    unset targetType targetHost targetPort targetUser \
          targetArgs targetPass targetName include preCmnd
}

main() {
  init
  log 3 "[BACKUPS START]"

  destDir=$destRoot/$(date +%Y)/$(date +%m)
  mkdir $v -p "$destDir" || err "couldn't access backups directory"

  log 3 "destination directory for backups is $destDir"

  for serverFile in $targetsDir/*; do
    [[ "$(jobs | wc -l)" -ge "${jobLimit:-1}" ]] && \
      wait -n
    ( backupTarget "${serverFile##*/}" ) &
  done
  wait
  log 3 "[BACKUPS DONE]"; echo
}

main "$@" &>> "${LOG:-/dev/stderr}"
